version: '3.8'

services:
  nginx:
    image: nginx:1.29-alpine
    container_name: nginx-lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./includes:/etc/nginx/includes/
    command: ["nginx","-g", "daemon off;"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
